<?php

namespace SIGE\SecurityManagerBundle\Repository;

/**
 * AppRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppRepository extends \Doctrine\ORM\EntityRepository {

    public function getModulesAccess($idApp, $roles) {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $modules = $qb->select('m')
                ->from('SecurityManagerBundle:Rol r,'
                        . ' SecurityManagerBundle:RolModule rm,'
                        . 'SecurityManagerBundle:Module', 'm')
                ->where("r.id = rm.role")
                ->andWhere("m.app = :idApp")
                ->andWhere("m.id = rm.module")
                ->andWhere("r.nombredescriptivo IN(:roles)")
                ->setParameter('roles', array_values($roles))
                ->setParameter('idApp', $idApp)
                ->getQuery()
                ->getArrayResult();
        return $modules;
    }

}
