<?php

namespace SIGE\SecurityManagerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AuthTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthTypeRepository extends EntityRepository
{
}
