<?php

namespace SIGE\SecurityManagerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IpAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IpAddressRepository extends EntityRepository
{
}
