<?php

namespace SIGE\SecurityManagerBundle\Repository;

/**
 * ModuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRepository extends \Doctrine\ORM\EntityRepository {

    public function findAll() {
        return $this->getEntityManager()
                        ->createQueryBuilder()
                        ->select(
                                'm.id', 'm.nombredescriptivo', 'm.codename', 'a.codename as app_codename', 'a.nombredescriptivo as app_nombredescriptivo', 'a.id as app_id'
                        )
                        ->from("Module.php", "m")->join('m.app', 'a')
                        ->getQuery()
                        ->getArrayResult();
    }

}
