<?php

namespace SIGE\SecurityManagerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolRepository extends EntityRepository
{
     public function getRolesUsers($idRol, $users) {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $users = $qb->select('u')
                ->from('SecurityManagerBundle:Rol', 'r')
                ->join('SecurityManagerBundle:Usuario', 'u')                     
                ->where("r.id = :idRol")
//                ->andWhere($qb->expr()->notIn($x, $qb))
                ->andWhere("u.id NOT IN(:users)")
                ->setParameter('users', array_values($users))
                ->setParameter('idRol', $idRol)
                ->getQuery()
                ->getResult();
        return $users;
    }
}
