<?php

namespace Proxies\__CG__\SIGE\ModelGeneratorBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Descriptor extends \SIGE\ModelGeneratorBundle\Entity\Descriptor implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'SIGE\\ModelGeneratorBundle\\Entity\\Descriptor' . "\0" . 'idnummodelo', '' . "\0" . 'SIGE\\ModelGeneratorBundle\\Entity\\Descriptor' . "\0" . 'idsubnummodelo', '' . "\0" . 'SIGE\\ModelGeneratorBundle\\Entity\\Descriptor' . "\0" . 'estado', '' . "\0" . 'SIGE\\ModelGeneratorBundle\\Entity\\Descriptor' . "\0" . 'tipodemodelo', '' . "\0" . 'SIGE\\ModelGeneratorBundle\\Entity\\Descriptor' . "\0" . 'clasificaciondeseguridad', '' . "\0" . 'SIGE\\ModelGeneratorBundle\\Entity\\Descriptor' . "\0" . 'piedefirma', '' . "\0" . 'SIGE\\ModelGeneratorBundle\\Entity\\Descriptor' . "\0" . 'notametodologica', '' . "\0" . 'SIGE\\ModelGeneratorBundle\\Entity\\Descriptor' . "\0" . 'periodicidad', '' . "\0" . 'SIGE\\ModelGeneratorBundle\\Entity\\Descriptor' . "\0" . 'aproximacion', '' . "\0" . 'SIGE\\ModelGeneratorBundle\\Entity\\Descriptor' . "\0" . 'nombredescriptivo', '' . "\0" . 'SIGE\\ModelGeneratorBundle\\Entity\\Descriptor' . "\0" . 'preguntaidentidad', '' . "\0" . 'SIGE\\ModelGeneratorBundle\\Entity\\Descriptor' . "\0" . 'sistemadeinformacion', '' . "\0" . 'SIGE\\ModelGeneratorBundle\\Entity\\Descriptor' . "\0" . 'paginas', '' . "\0" . 'SIGE\\ModelGeneratorBundle\\Entity\\Descriptor' . "\0" . 'roles');
        }

        return array('__isInitialized__', '' . "\0" . 'SIGE\\ModelGeneratorBundle\\Entity\\Descriptor' . "\0" . 'idnummodelo', '' . "\0" . 'SIGE\\ModelGeneratorBundle\\Entity\\Descriptor' . "\0" . 'idsubnummodelo', '' . "\0" . 'SIGE\\ModelGeneratorBundle\\Entity\\Descriptor' . "\0" . 'estado', '' . "\0" . 'SIGE\\ModelGeneratorBundle\\Entity\\Descriptor' . "\0" . 'tipodemodelo', '' . "\0" . 'SIGE\\ModelGeneratorBundle\\Entity\\Descriptor' . "\0" . 'clasificaciondeseguridad', '' . "\0" . 'SIGE\\ModelGeneratorBundle\\Entity\\Descriptor' . "\0" . 'piedefirma', '' . "\0" . 'SIGE\\ModelGeneratorBundle\\Entity\\Descriptor' . "\0" . 'notametodologica', '' . "\0" . 'SIGE\\ModelGeneratorBundle\\Entity\\Descriptor' . "\0" . 'periodicidad', '' . "\0" . 'SIGE\\ModelGeneratorBundle\\Entity\\Descriptor' . "\0" . 'aproximacion', '' . "\0" . 'SIGE\\ModelGeneratorBundle\\Entity\\Descriptor' . "\0" . 'nombredescriptivo', '' . "\0" . 'SIGE\\ModelGeneratorBundle\\Entity\\Descriptor' . "\0" . 'preguntaidentidad', '' . "\0" . 'SIGE\\ModelGeneratorBundle\\Entity\\Descriptor' . "\0" . 'sistemadeinformacion', '' . "\0" . 'SIGE\\ModelGeneratorBundle\\Entity\\Descriptor' . "\0" . 'paginas', '' . "\0" . 'SIGE\\ModelGeneratorBundle\\Entity\\Descriptor' . "\0" . 'roles');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Descriptor $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setIdnummodelo($idnummodelo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdnummodelo', array($idnummodelo));

        return parent::setIdnummodelo($idnummodelo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdnummodelo()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getIdnummodelo();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdnummodelo', array());

        return parent::getIdnummodelo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdsubnummodelo($idsubnummodelo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdsubnummodelo', array($idsubnummodelo));

        return parent::setIdsubnummodelo($idsubnummodelo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdsubnummodelo()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getIdsubnummodelo();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdsubnummodelo', array());

        return parent::getIdsubnummodelo();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipodemodelo($tipodemodelo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipodemodelo', array($tipodemodelo));

        return parent::setTipodemodelo($tipodemodelo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipodemodelo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipodemodelo', array());

        return parent::getTipodemodelo();
    }

    /**
     * {@inheritDoc}
     */
    public function setClasificaciondeseguridad($clasificaciondeseguridad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClasificaciondeseguridad', array($clasificaciondeseguridad));

        return parent::setClasificaciondeseguridad($clasificaciondeseguridad);
    }

    /**
     * {@inheritDoc}
     */
    public function getClasificaciondeseguridad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClasificaciondeseguridad', array());

        return parent::getClasificaciondeseguridad();
    }

    /**
     * {@inheritDoc}
     */
    public function setPiedefirma($piedefirma)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPiedefirma', array($piedefirma));

        return parent::setPiedefirma($piedefirma);
    }

    /**
     * {@inheritDoc}
     */
    public function getPiedefirma()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPiedefirma', array());

        return parent::getPiedefirma();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeriodicidad($periodicidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeriodicidad', array($periodicidad));

        return parent::setPeriodicidad($periodicidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriodicidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriodicidad', array());

        return parent::getPeriodicidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setAproximacion($aproximacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAproximacion', array($aproximacion));

        return parent::setAproximacion($aproximacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getAproximacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAproximacion', array());

        return parent::getAproximacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombredescriptivo($nombredescriptivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombredescriptivo', array($nombredescriptivo));

        return parent::setNombredescriptivo($nombredescriptivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombredescriptivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombredescriptivo', array());

        return parent::getNombredescriptivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreguntaidentidad($preguntaidentidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreguntaidentidad', array($preguntaidentidad));

        return parent::setPreguntaidentidad($preguntaidentidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreguntaidentidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreguntaidentidad', array());

        return parent::getPreguntaidentidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setSistemadeinformacion($sistemadeinformacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSistemadeinformacion', array($sistemadeinformacion));

        return parent::setSistemadeinformacion($sistemadeinformacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getSistemadeinformacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSistemadeinformacion', array());

        return parent::getSistemadeinformacion();
    }

    /**
     * {@inheritDoc}
     */
    public function addPagina(\SIGE\ModelGeneratorBundle\Entity\Pagina $pagina)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPagina', array($pagina));

        return parent::addPagina($pagina);
    }

    /**
     * {@inheritDoc}
     */
    public function removePagina(\SIGE\ModelGeneratorBundle\Entity\Pagina $pagina)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePagina', array($pagina));

        return parent::removePagina($pagina);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaginas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaginas', array());

        return parent::getPaginas();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotametodologica($notametodologica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotametodologica', array($notametodologica));

        return parent::setNotametodologica($notametodologica);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotametodologica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotametodologica', array());

        return parent::getNotametodologica();
    }

    /**
     * {@inheritDoc}
     */
    public function addRole(\SIGE\ModelGeneratorBundle\Entity\Roldescriptor $roles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRole', array($roles));

        return parent::addRole($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRole(\SIGE\ModelGeneratorBundle\Entity\Roldescriptor $roles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRole', array($roles));

        return parent::removeRole($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', array());

        return parent::getRoles();
    }

}
