<?php

namespace Proxies\__CG__\SIGE\RecordsClassifiersBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Piedefirma extends \SIGE\RecordsClassifiersBundle\Entity\Piedefirma implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Piedefirma' . "\0" . 'id', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Piedefirma' . "\0" . 'denominaciondelpie', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Piedefirma' . "\0" . 'primercargo', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Piedefirma' . "\0" . 'segundocargo', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Piedefirma' . "\0" . 'notadecertificacion', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Piedefirma' . "\0" . 'sistemadeinformacion');
        }

        return array('__isInitialized__', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Piedefirma' . "\0" . 'id', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Piedefirma' . "\0" . 'denominaciondelpie', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Piedefirma' . "\0" . 'primercargo', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Piedefirma' . "\0" . 'segundocargo', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Piedefirma' . "\0" . 'notadecertificacion', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Piedefirma' . "\0" . 'sistemadeinformacion');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Piedefirma $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDenominaciondelpie($denominaciondelpie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDenominaciondelpie', array($denominaciondelpie));

        return parent::setDenominaciondelpie($denominaciondelpie);
    }

    /**
     * {@inheritDoc}
     */
    public function getDenominaciondelpie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDenominaciondelpie', array());

        return parent::getDenominaciondelpie();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrimercargo($primercargo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrimercargo', array($primercargo));

        return parent::setPrimercargo($primercargo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimercargo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimercargo', array());

        return parent::getPrimercargo();
    }

    /**
     * {@inheritDoc}
     */
    public function setSegundocargo($segundocargo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSegundocargo', array($segundocargo));

        return parent::setSegundocargo($segundocargo);
    }

    /**
     * {@inheritDoc}
     */
    public function getSegundocargo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSegundocargo', array());

        return parent::getSegundocargo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotadecertificacion($notadecertificacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotadecertificacion', array($notadecertificacion));

        return parent::setNotadecertificacion($notadecertificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotadecertificacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotadecertificacion', array());

        return parent::getNotadecertificacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setSistemadeinformacion(\SIGE\RecordsClassifiersBundle\Entity\Sistemadeinformacion $sistemadeinformacion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSistemadeinformacion', array($sistemadeinformacion));

        return parent::setSistemadeinformacion($sistemadeinformacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getSistemadeinformacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSistemadeinformacion', array());

        return parent::getSistemadeinformacion();
    }

}
