<?php

namespace Proxies\__CG__\SIGE\RecordsClassifiersBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tematica extends \SIGE\RecordsClassifiersBundle\Entity\Tematica implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Tematica' . "\0" . 'id', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Tematica' . "\0" . 'nombredescriptivo', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Tematica' . "\0" . 'descripcion', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Tematica' . "\0" . 'indicadores', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Tematica' . "\0" . 'aspectos', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Tematica' . "\0" . 'tipoindicadoraspecto');
        }

        return array('__isInitialized__', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Tematica' . "\0" . 'id', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Tematica' . "\0" . 'nombredescriptivo', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Tematica' . "\0" . 'descripcion', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Tematica' . "\0" . 'indicadores', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Tematica' . "\0" . 'aspectos', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Tematica' . "\0" . 'tipoindicadoraspecto');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tematica $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombredescriptivo($nombredescriptivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombredescriptivo', array($nombredescriptivo));

        return parent::setNombredescriptivo($nombredescriptivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombredescriptivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombredescriptivo', array());

        return parent::getNombredescriptivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndicadores($indicadores)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndicadores', array($indicadores));

        return parent::setIndicadores($indicadores);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndicadores()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndicadores', array());

        return parent::getIndicadores();
    }

    /**
     * {@inheritDoc}
     */
    public function setAspectos($aspectos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAspectos', array($aspectos));

        return parent::setAspectos($aspectos);
    }

    /**
     * {@inheritDoc}
     */
    public function getAspectos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAspectos', array());

        return parent::getAspectos();
    }

    /**
     * {@inheritDoc}
     */
    public function addIndicadore(\SIGE\RecordsClassifiersBundle\Entity\Indicador $indicadore)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIndicadore', array($indicadore));

        return parent::addIndicadore($indicadore);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIndicadore(\SIGE\RecordsClassifiersBundle\Entity\Indicador $indicadore)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIndicadore', array($indicadore));

        return parent::removeIndicadore($indicadore);
    }

    /**
     * {@inheritDoc}
     */
    public function addAspecto(\SIGE\RecordsClassifiersBundle\Entity\Aspecto $aspecto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAspecto', array($aspecto));

        return parent::addAspecto($aspecto);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAspecto(\SIGE\RecordsClassifiersBundle\Entity\Aspecto $aspecto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAspecto', array($aspecto));

        return parent::removeAspecto($aspecto);
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', array($descripcion));

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', array());

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoindicadoraspecto($tipoindicadoraspecto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoindicadoraspecto', array($tipoindicadoraspecto));

        return parent::setTipoindicadoraspecto($tipoindicadoraspecto);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoindicadoraspecto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoindicadoraspecto', array());

        return parent::getTipoindicadoraspecto();
    }

}
