<?php

namespace Proxies\__CG__\SIGE\RecordsClassifiersBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Sistemadeinformacion extends \SIGE\RecordsClassifiersBundle\Entity\Sistemadeinformacion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Sistemadeinformacion' . "\0" . 'id', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Sistemadeinformacion' . "\0" . 'alias', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Sistemadeinformacion' . "\0" . 'imagenlogo', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Sistemadeinformacion' . "\0" . 'tipodearchivo', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Sistemadeinformacion' . "\0" . 'denominacion', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Sistemadeinformacion' . "\0" . 'registros', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Sistemadeinformacion' . "\0" . 'indicadores');
        }

        return array('__isInitialized__', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Sistemadeinformacion' . "\0" . 'id', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Sistemadeinformacion' . "\0" . 'alias', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Sistemadeinformacion' . "\0" . 'imagenlogo', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Sistemadeinformacion' . "\0" . 'tipodearchivo', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Sistemadeinformacion' . "\0" . 'denominacion', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Sistemadeinformacion' . "\0" . 'registros', '' . "\0" . 'SIGE\\RecordsClassifiersBundle\\Entity\\Sistemadeinformacion' . "\0" . 'indicadores');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Sistemadeinformacion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlias($alias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlias', array($alias));

        return parent::setAlias($alias);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlias', array());

        return parent::getAlias();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipodearchivo($tipodearchivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipodearchivo', array($tipodearchivo));

        return parent::setTipodearchivo($tipodearchivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipodearchivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipodearchivo', array());

        return parent::getTipodearchivo();
    }

    /**
     * {@inheritDoc}
     */
    public function addRegistro(\SIGE\RecordsClassifiersBundle\Entity\Registro $registros)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRegistro', array($registros));

        return parent::addRegistro($registros);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRegistro(\SIGE\RecordsClassifiersBundle\Entity\Registro $registros)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRegistro', array($registros));

        return parent::removeRegistro($registros);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistros()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistros', array());

        return parent::getRegistros();
    }

    /**
     * {@inheritDoc}
     */
    public function setDenominacion($denominacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDenominacion', array($denominacion));

        return parent::setDenominacion($denominacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDenominacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDenominacion', array());

        return parent::getDenominacion();
    }

    /**
     * {@inheritDoc}
     */
    public function addIndicadore(\SIGE\RecordsClassifiersBundle\Entity\Indicador $indicadores)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIndicadore', array($indicadores));

        return parent::addIndicadore($indicadores);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndicadores()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndicadores', array());

        return parent::getIndicadores();
    }

    /**
     * {@inheritDoc}
     */
    public function removeIndicadore(\SIGE\RecordsClassifiersBundle\Entity\Indicador $indicadores)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIndicadore', array($indicadores));

        return parent::removeIndicadore($indicadores);
    }

    /**
     * {@inheritDoc}
     */
    public function setImagenlogo($imagenlogo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagenlogo', array($imagenlogo));

        return parent::setImagenlogo($imagenlogo);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagenlogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagenlogo', array());

        return parent::getImagenlogo();
    }

}
