imports:
    - { resource: parameters.yml }
    - { resource: parameters_boson.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@DisciplineBundle/Resources/config/services.yml" }
    - { resource: "@SigeBundle/Resources/config/services.yml" }
    - { resource: "@AdminBundle/Resources/config/services.yml" }
    - { resource: "@DataEntryBundle/Resources/config/services.yml" }
    - { resource: "@ModelGeneratorBundle/Resources/config/services.yml" }
    - { resource: "@RecordsClassifiersBundle/Resources/config/services.yml" }
    - { resource: "@SecurityManagerBundle/Resources/config/services.yml" }
    - { resource: "@ToolsBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
#parameters:
#    locale: es

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: false
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        #cuando se cierra el navegador se cierra la sesion
        cookie_lifetime: 0
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

sensio_framework_extra:
    view: { annotations: false }
    router: { annotations: true }
    request: { converters: true }
    
fos_rest:
    body_listener: true
    param_fetcher_listener: true
    disable_csrf_role: ROLE_API
    format_listener:
        enabled: true
        rules:
            - { path: ^/, priorities: json, fallback_format: json, prefer_extension: false }
    view:
        view_response_listener: 'force'
        formats:           
            json: true


nelmio_api_doc:
    name: Documentación SIGE