<?php

namespace SIGE\RecordsClassifiersBundle\Repository;

/**
 * AspectoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AspectoRepository extends \Doctrine\ORM\EntityRepository
{
}
