<?php

namespace SIGE\RecordsClassifiersBundle\Repository;

/**
 * CentroinformanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentroinformanteRepository extends \Doctrine\ORM\EntityRepository
{
}
