<?php

namespace SIGE\RecordsClassifiersBundle\Repository;

/**
 * ClasificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasificacionRepository extends \Doctrine\ORM\EntityRepository
{

    public function getClasificationsByClasificator($id,$start,$limit){


        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder()->select('c')
            ->from('RecordsClassifiersBundle:Clasificacion', 'c')
            ->where('c.clasificador = ?1')->orderBy('c.id')
            ->setParameter(1, $id)->setFirstResult($start)->setMaxResults($limit);

        return $query->getQuery()->getResult();

    }
}
