<?php

namespace SIGE\RecordsClassifiersBundle\Repository;

/**
 * ClasificadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasificadorRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($criteria)
    {

        $em = $this->getEntityManager();


        $search = $em->createQueryBuilder()->select('u')
            ->from('RecordsClassifiersBundle:Clasificador', 'u')
            ->where('u.id LIKE ?1')
            ->orWhere('u.nombredescriptivo LIKE ?1 ')
            ->orWhere('u.alias LIKE ?1')
            ->setParameter(1, '%'.$criteria.'%');



        return $search->getQuery()->getResult();
    }
}
