<?php

namespace SIGE\RecordsClassifiersBundle\Repository;

/**
 * ClasificacionSeguridadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasificacionSeguridadRepository extends \Doctrine\ORM\EntityRepository
{
}
