<?php

namespace SIGE\RecordsClassifiersBundle\Repository;

/**
 * ClasificacionCentroInformanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasificacionCentroInformanteRepository extends \Doctrine\ORM\EntityRepository
{
}
