<?php

namespace SIGE\RecordsClassifiersBundle\Repository;

/**
 * OmeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OmeRepository extends \Doctrine\ORM\EntityRepository
{
}
