<?php

namespace SIGE\RecordsClassifiersBundle\Repository;

/**
 * OteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OteRepository extends \Doctrine\ORM\EntityRepository
{
}
