<?php

namespace SIGE\RecordsClassifiersBundle\Repository;

/**
 * PiedefirmaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiedefirmaRepository extends \Doctrine\ORM\EntityRepository
{
}
