<?php

namespace SIGE\RecordsClassifiersBundle\Repository;

/**
 * SistemadeinformacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SistemadeinformacionRepository extends \Doctrine\ORM\EntityRepository
{
}
