<?php

namespace SIGE\RecordsClassifiersBundle\Repository;

/**
 * TematicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TematicaRepository extends \Doctrine\ORM\EntityRepository
{
}
