<?php

namespace SIGE\RecordsClassifiersBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TipoIndicadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoIndicadorRepository extends EntityRepository
{
}
