<?php

namespace SIGE\DisciplineBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConvenioinformativoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConvenioinformativoRepository extends EntityRepository
{
}
