<?php

namespace SIGE\DisciplineBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConvenioinformativoencuestaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConvenioinformativoencuestaRepository extends EntityRepository
{
}
