<?php

namespace SIGE\DisciplineBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConvenioinformativohistorialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConvenioinformativohistorialRepository extends EntityRepository
{
}
