<?php

namespace SIGE\DisciplineBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConvenioinformativomodeloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConvenioinformativomodeloRepository extends EntityRepository
{
}
