<?php

namespace SIGE\ModelGeneratorBundle\Repository;

/**
 * DescriptorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DescriptorRepository extends \Doctrine\ORM\EntityRepository
{
}
