<?php

namespace SIGE\ModelGeneratorBundle\Repository;

/**
 * PaginaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaginaRepository extends \Doctrine\ORM\EntityRepository
{
}
