<?php

namespace SIGE\ModelGeneratorBundle\Repository;

/**
 * SeccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeccionRepository extends \Doctrine\ORM\EntityRepository
{
}
