<?php

namespace SIGE\ModelGeneratorBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TipoDeConfiguracionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoDeConfiguracionRepository extends EntityRepository
{
}
