<?php

namespace SIGE\ModelGeneratorBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VarianteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VarianteRepository extends EntityRepository
{
}
