<?php

namespace SIGE\DataEntryBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TBEncuestaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TBEncuestaRepository extends EntityRepository
{
}
