<?php

namespace SIGE\ToolsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MaestroclasificadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaestroclasificadorRepository extends EntityRepository
{
}
