<?php

namespace SIGE\ToolsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MaestroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaestroRepository extends EntityRepository
{
}
