<?php

namespace SIGE\ToolsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MaestroregistroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaestroregistroRepository extends EntityRepository
{
}
